//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExcelTemplate1 {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet1 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button1;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox checkBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckedListBox checkedListBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.DateTimePicker dateTimePicker1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label2;
        
        internal Microsoft.Office.Tools.Excel.Controls.LinkLabel linkLabel1;
        
        internal Microsoft.Office.Tools.Excel.Controls.ListBox listBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.MaskedTextBox maskedTextBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.ListView listView1;
        
        internal Microsoft.Office.Tools.Excel.Controls.MonthCalendar monthCalendar1;
        
        internal Microsoft.Office.Tools.Excel.Controls.NumericUpDown numericUpDown1;
        
        internal Microsoft.Office.Tools.Excel.Controls.PictureBox pictureBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.RadioButton radioButton1;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox textBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.TreeView treeView1;
        
        internal Microsoft.Office.Tools.Excel.Controls.WebBrowser webBrowser1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button2;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox checkBox2;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckedListBox checkedListBox2;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBox2;
        
        internal Microsoft.Office.Tools.Excel.Controls.DataGridView dataGridView1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Label label3;
        
        internal Microsoft.Office.Tools.Excel.Controls.LinkLabel linkLabel2;
        
        internal Microsoft.Office.Tools.Excel.Controls.PropertyGrid propertyGrid1;
        
        internal Microsoft.Office.Tools.Excel.Controls.TreeView treeView2;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet1(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet1", "Sheet1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet1 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.button1 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "10F28D8141FA61149C91B67E1B304BF53FB3C1", "10F28D8141FA61149C91B67E1B304BF53FB3C1", this, "button1");
            this.checkBox1 = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "27B9D079D2BEA824F642904C27836A3B29E412", "27B9D079D2BEA824F642904C27836A3B29E412", this, "checkBox1");
            this.checkedListBox1 = new Microsoft.Office.Tools.Excel.Controls.CheckedListBox(Globals.Factory, this.ItemProvider, this.HostContext, "34054D9663ED7034913383B937960401CC9343", "34054D9663ED7034913383B937960401CC9343", this, "checkedListBox1");
            this.comboBox1 = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "429DEE058448EA44ECF4A8D54BAEE7E6A102C4", "429DEE058448EA44ECF4A8D54BAEE7E6A102C4", this, "comboBox1");
            this.dateTimePicker1 = new Microsoft.Office.Tools.Excel.Controls.DateTimePicker(Globals.Factory, this.ItemProvider, this.HostContext, "57875F0AF552025498C5A839554669C2EEE4C5", "57875F0AF552025498C5A839554669C2EEE4C5", this, "dateTimePicker1");
            this.label1 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "63AF5FE4C6A0C0648626A9F8621F3615E47F86", "63AF5FE4C6A0C0648626A9F8621F3615E47F86", this, "label1");
            this.label2 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "74899A23C79CB4741A27B703770EA5DF7421C7", "74899A23C79CB4741A27B703770EA5DF7421C7", this, "label2");
            this.linkLabel1 = new Microsoft.Office.Tools.Excel.Controls.LinkLabel(Globals.Factory, this.ItemProvider, this.HostContext, "9B4A9339E99D9694D1A9B7CF98A1300C13A859", "9B4A9339E99D9694D1A9B7CF98A1300C13A859", this, "linkLabel1");
            this.listBox1 = new Microsoft.Office.Tools.Excel.Controls.ListBox(Globals.Factory, this.ItemProvider, this.HostContext, "109BD701B184C8147711A696136EF72E6ED4E1", "109BD701B184C8147711A696136EF72E6ED4E1", this, "listBox1");
            this.maskedTextBox1 = new Microsoft.Office.Tools.Excel.Controls.MaskedTextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1BB695F0113CF9149851BDFA12E155BC8761F1", "1BB695F0113CF9149851BDFA12E155BC8761F1", this, "maskedTextBox1");
            this.listView1 = new Microsoft.Office.Tools.Excel.Controls.ListView(Globals.Factory, this.ItemProvider, this.HostContext, "12B265D591494A14BF3194B7138EE31E439031", "12B265D591494A14BF3194B7138EE31E439031", this, "listView1");
            this.monthCalendar1 = new Microsoft.Office.Tools.Excel.Controls.MonthCalendar(Globals.Factory, this.ItemProvider, this.HostContext, "1270477DF16745147841B898163E72996659C1", "1270477DF16745147841B898163E72996659C1", this, "monthCalendar1");
            this.numericUpDown1 = new Microsoft.Office.Tools.Excel.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "11508FCE4122E814B381A6621EAD8681709EF1", "11508FCE4122E814B381A6621EAD8681709EF1", this, "numericUpDown1");
            this.pictureBox1 = new Microsoft.Office.Tools.Excel.Controls.PictureBox(Globals.Factory, this.ItemProvider, this.HostContext, "104EC5EB71152114BAE1B340152E8AC97B5611", "104EC5EB71152114BAE1B340152E8AC97B5611", this, "pictureBox1");
            this.radioButton1 = new Microsoft.Office.Tools.Excel.Controls.RadioButton(Globals.Factory, this.ItemProvider, this.HostContext, "10FF290E1180A314EDA1A47010BB546FFC5D81", "10FF290E1180A314EDA1A47010BB546FFC5D81", this, "radioButton1");
            this.textBox1 = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1DB5D16501914F1416018B661E6928251F24E1", "1DB5D16501914F1416018B661E6928251F24E1", this, "textBox1");
            this.treeView1 = new Microsoft.Office.Tools.Excel.Controls.TreeView(Globals.Factory, this.ItemProvider, this.HostContext, "182D9FA181DB17145291A58A110793E2D40481", "182D9FA181DB17145291A58A110793E2D40481", this, "treeView1");
            this.webBrowser1 = new Microsoft.Office.Tools.Excel.Controls.WebBrowser(Globals.Factory, this.ItemProvider, this.HostContext, "1FACE2E8E1978414A6E1996F16851FCBE12C81", "1FACE2E8E1978414A6E1996F16851FCBE12C81", this, "webBrowser1");
            this.button2 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "24DDC10DD2F2C324E4F297602B8154AF66D042", "24DDC10DD2F2C324E4F297602B8154AF66D042", this, "button2");
            this.checkBox2 = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2AB979D2A233602409F2B8C722EF90C908BE42", "2AB979D2A233602409F2B8C722EF90C908BE42", this, "checkBox2");
            this.checkedListBox2 = new Microsoft.Office.Tools.Excel.Controls.CheckedListBox(Globals.Factory, this.ItemProvider, this.HostContext, "2BFC27A30263B224A7F28BFA25AB3AC082ACC2", "2BFC27A30263B224A7F28BFA25AB3AC082ACC2", this, "checkedListBox2");
            this.comboBox2 = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "2BD54ABA32239C242962BDAD2B78CC5D0B7692", "2BD54ABA32239C242962BDAD2B78CC5D0B7692", this, "comboBox2");
            this.dataGridView1 = new Microsoft.Office.Tools.Excel.Controls.DataGridView(Globals.Factory, this.ItemProvider, this.HostContext, "2D5D80EE723B9724B322B0852EB56DAB705AD2", "2D5D80EE723B9724B322B0852EB56DAB705AD2", this, "dataGridView1");
            this.label3 = new Microsoft.Office.Tools.Excel.Controls.Label(Globals.Factory, this.ItemProvider, this.HostContext, "2F147A4F02895024ED32BE2422C99971B4BDA2", "2F147A4F02895024ED32BE2422C99971B4BDA2", this, "label3");
            this.linkLabel2 = new Microsoft.Office.Tools.Excel.Controls.LinkLabel(Globals.Factory, this.ItemProvider, this.HostContext, "2C5EA609C250A124B4C2AACA267980134F2B02", "2C5EA609C250A124B4C2AACA267980134F2B02", this, "linkLabel2");
            this.propertyGrid1 = new Microsoft.Office.Tools.Excel.Controls.PropertyGrid(Globals.Factory, this.ItemProvider, this.HostContext, "214ACFD7828CB324F252AAB828765D87E50572", "214ACFD7828CB324F252AAB828765D87E50572", this, "propertyGrid1");
            this.treeView2 = new Microsoft.Office.Tools.Excel.Controls.TreeView(Globals.Factory, this.ItemProvider, this.HostContext, "295D9A3C524B1B2400B2A2DE277C9B5A5A0B72", "295D9A3C524B1B2400B2A2DE277C9B5A5A0B72", this, "treeView2");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Name = "button1";
            this.button1.Text = "button1";
            this.button1.UseVisualStyleBackColor = false;
            // 
            // checkBox1
            // 
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Text = "checkBox1";
            // 
            // checkedListBox1
            // 
            this.checkedListBox1.Name = "checkedListBox1";
            // 
            // comboBox1
            // 
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Text = "comboBox1";
            // 
            // dateTimePicker1
            // 
            this.dateTimePicker1.Name = "dateTimePicker1";
            // 
            // label1
            // 
            this.label1.Name = "label1";
            this.label1.Text = "label1";
            // 
            // label2
            // 
            this.label2.Name = "label2";
            this.label2.Text = "label2";
            // 
            // linkLabel1
            // 
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Text = "linkLabel1";
            // 
            // listBox1
            // 
            this.listBox1.ItemHeight = 20;
            this.listBox1.Name = "listBox1";
            // 
            // maskedTextBox1
            // 
            this.maskedTextBox1.Name = "maskedTextBox1";
            // 
            // listView1
            // 
            this.listView1.HideSelection = false;
            this.listView1.Name = "listView1";
            this.listView1.Text = "listView1";
            this.listView1.UseCompatibleStateImageBehavior = false;
            // 
            // monthCalendar1
            // 
            this.monthCalendar1.Name = "monthCalendar1";
            // 
            // numericUpDown1
            // 
            this.numericUpDown1.Name = "numericUpDown1";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Text = "pictureBox1";
            // 
            // radioButton1
            // 
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Text = "radioButton1";
            // 
            // textBox1
            // 
            this.textBox1.Name = "textBox1";
            this.textBox1.Text = "textBox1";
            // 
            // treeView1
            // 
            this.treeView1.Name = "treeView1";
            this.treeView1.Text = "treeView1";
            // 
            // webBrowser1
            // 
            this.webBrowser1.Name = "webBrowser1";
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Name = "button2";
            this.button2.Text = "button2";
            this.button2.UseVisualStyleBackColor = false;
            // 
            // checkBox2
            // 
            this.checkBox2.Name = "checkBox2";
            this.checkBox2.Text = "checkBox2";
            // 
            // checkedListBox2
            // 
            this.checkedListBox2.Name = "checkedListBox2";
            // 
            // comboBox2
            // 
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Text = "comboBox2";
            // 
            // dataGridView1
            // 
            this.dataGridView1.ColumnHeadersHeight = 34;
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersWidth = 62;
            this.dataGridView1.Text = "dataGridView1";
            // 
            // label3
            // 
            this.label3.Name = "label3";
            this.label3.Text = "label3";
            // 
            // linkLabel2
            // 
            this.linkLabel2.Name = "linkLabel2";
            this.linkLabel2.Text = "linkLabel2";
            // 
            // propertyGrid1
            // 
            this.propertyGrid1.Name = "propertyGrid1";
            // 
            // treeView2
            // 
            this.treeView2.Name = "treeView2";
            this.treeView2.Text = "treeView2";
            // 
            // Sheet1
            // 
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.button1.BindingContext = this.BindingContext;
            this.checkBox1.BindingContext = this.BindingContext;
            this.checkedListBox1.BindingContext = this.BindingContext;
            this.comboBox1.BindingContext = this.BindingContext;
            this.dateTimePicker1.BindingContext = this.BindingContext;
            this.label1.BindingContext = this.BindingContext;
            this.label2.BindingContext = this.BindingContext;
            this.linkLabel1.BindingContext = this.BindingContext;
            this.listBox1.BindingContext = this.BindingContext;
            this.maskedTextBox1.BindingContext = this.BindingContext;
            this.listView1.BindingContext = this.BindingContext;
            this.monthCalendar1.BindingContext = this.BindingContext;
            this.numericUpDown1.BindingContext = this.BindingContext;
            this.pictureBox1.BindingContext = this.BindingContext;
            this.radioButton1.BindingContext = this.BindingContext;
            this.textBox1.BindingContext = this.BindingContext;
            this.treeView1.BindingContext = this.BindingContext;
            this.webBrowser1.BindingContext = this.BindingContext;
            this.button2.BindingContext = this.BindingContext;
            this.checkBox2.BindingContext = this.BindingContext;
            this.checkedListBox2.BindingContext = this.BindingContext;
            this.comboBox2.BindingContext = this.BindingContext;
            this.dataGridView1.BindingContext = this.BindingContext;
            this.label3.BindingContext = this.BindingContext;
            this.linkLabel2.BindingContext = this.BindingContext;
            this.propertyGrid1.BindingContext = this.BindingContext;
            this.treeView2.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet1 _Sheet1;
        
        internal static Sheet1 Sheet1 {
            get {
                return _Sheet1;
            }
            set {
                if ((_Sheet1 == null)) {
                    _Sheet1 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
